export const EVENT_TYPES = [
  { value: 'conference', label: 'Conférence' },
  { value: 'seminar', label: 'Séminaire' },
  { value: 'workshop', label: 'Atelier' },
  { value: 'concert', label: 'Concert' },
  { value: 'festival', label: 'Festival' },
  { value: 'exhibition', label: 'Exposition' },
  { value: 'trade_show', label: 'Salon professionnel' },
  { value: 'networking', label: 'Networking' },
  { value: 'ceremony', label: 'Cérémonie' },
  { value: 'gala', label: 'Gala' },
  { value: 'party', label: 'Soirée' },
  { value: 'sports', label: 'Événement sportif' },
  { value: 'cultural', label: 'Événement culturel' },
  { value: 'charity', label: 'Événement caritatif' },
  { value: 'launch', label: 'Lancement de produit' },
  { value: 'meetup', label: 'Meetup' },
  { value: 'hackathon', label: 'Hackathon' },
  { value: 'wedding', label: 'Mariage' },
  { value: 'birthday', label: 'Anniversaire' },
  { value: 'religious', label: 'Événement religieux' },
  { value: 'educational', label: 'Événement éducatif' },
  { value: 'food_drink', label: 'Gastronomie et boissons' },
  { value: 'fashion', label: 'Mode' },
  { value: 'art', label: 'Art' },
  { value: 'theater', label: 'Théâtre' },
  { value: 'cinema', label: 'Cinéma' },
  { value: 'dance', label: 'Danse' },
  { value: 'comedy', label: 'Humour' },
  { value: 'gaming', label: 'Gaming' },
  { value: 'other', label: 'Autre' }
];